### ISSUE TITLE
[Question] Where I could buy it

### ISSUE THREAD

**Issue by Visit-Learn** [WIZnet-Azure-Sphere/ASG210_App#2]
Hi,

Could I know where I could buy ASG210? And what's different between ASG200 with ASG210?
Thank you so much.

**Comment by irinakim12** [comment]
Hi
As far as I know, the AGS200 is not yet sold, and it is available as a prototype. AGS201 seems to be in development.

**Comment by joon874** [comment]
@Visit-Learn Hi, ASG210 has more interfaces, UART, I2C, GPIOs and Dual-ethernet, than ASG200 which has only dual-ethernet. ASG210 is now in preliminary stage. But we have some sample boards for pre-market. 
So, would you like to share the information; what purpose you have and how many you consider to buy (I do not have many..)?
please contact my e-mail. <lawrence@wiznet.io>
